// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX64V_3teUPMCtjjbaMSPI0q6V-SmxRdk',
    appId: '1:849111399996:android:06fb9a0360943389598d39',
    messagingSenderId: '849111399996',
    projectId: 'smart-travel-planner-app-7015',
    databaseURL: 'https://smart-travel-planner-app-7015-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-travel-planner-app-7015.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Tv1OQ5Wc5KTRk4qZ3AMS8tPObToyPHo',
    appId: '1:849111399996:ios:a62dc688d34af329598d39',
    messagingSenderId: '849111399996',
    projectId: 'smart-travel-planner-app-7015',
    databaseURL: 'https://smart-travel-planner-app-7015-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-travel-planner-app-7015.firebasestorage.app',
    androidClientId: '849111399996-5j1rhiq8r2akvgp6j3qh0s8c2ss0hqum.apps.googleusercontent.com',
    iosClientId: '849111399996-c0qrj2o04mlqombigmrfmlj229kmcemp.apps.googleusercontent.com',
    iosBundleId: 'com.parth.io.task.travelDude',
  );

}